
namespace: neuvector

image:
  registry: docker.io
  repository: fluent/fluent-bit
  tag: 1.0.0
  imagePullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: 1

replicaCount: 1

azure_log_workspace_id: <WORKSPACE_ID>

azure_log_workspace_shared_key: <WORKSPACE_SHARED_KEY>

enableSecret: false